name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python --version
          python3 --version
          python -m pip install --upgrade pip 
          pip install whispers
          #whispers . >> whispers_scan_report.json
      
      - name: Whispers Scan
        run: |
          whispers . >> whispers_scan_report.json
      
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: whispers_scan_report.json 
          
      - name: Gitleaks Scan
        run: |
          sudo apt-get update
          sudo apt-get install wget tar -y 
          wget --version
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.0.6/gitleaks_8.0.6_linux_x64.tar.gz
          tar -xf gitleaks_8.0.6_linux_x64.tar.gz 
          chmod +x gitleaks
          mv gitleaks /usr/local/bin/
          gitleaks detect --report-format json --report-path gitleaks_scan_report.json --exit-code 0
          
        
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: gitleaks_scan_report.json 
          
      - name: git-secrets Scan
        run: |
          cd ..
          ls -la
          mkdir git-secrets
          cd git-secrets
          wget https://github.com/awslabs/git-secrets/archive/refs/heads/master.zip
          unzip master.zip 
          chmod -R 777 git-secrets-master
          chmod -R 777 /usr/local/share/man/man1
          ls -la
          cd git-secrets-master
          ls -la
          make install
          
          #cd ..
          #git secrets --install
          #git secrets --register-aws
          
          #git secrets --scan &> get-secrets-scan-output.json
          #git secrets --scan-history &> get-secrets-scan-history-output.json
          
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: |
            get-secrets-scan-output.json 
            get-secrets-scan-history-output.json
