name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python --version
          python3 --version
          python -m pip install --upgrade pip 
          pip install whispers
          sudo apt-get update
          sudo apt-get install wget tar -y 
          pip install truffleHog
      
      - name: Whispers Scan
        run: |
          whispers . >> whispers_scan_report.json
          
      - name: Gitleaks Scan
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.0.6/gitleaks_8.0.6_linux_x64.tar.gz
          tar -xf gitleaks_8.0.6_linux_x64.tar.gz 
          chmod +x gitleaks
          mv gitleaks /usr/local/bin/
          gitleaks detect --report-format json --report-path gitleaks_scan_report.json --exit-code 0
          
        
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: |
            whispers_scan_report.json 
            gitleaks_scan_report.json 
          
      - name: Set up git-secrets
        run: |
          rm -rf LICENSE , README.md , gitleaks_8.0.6_linux_x64.tar.gz , gitleaks_scan_report.json , whispers_scan_report.json , .github , .gitleaks.toml
          cd ..
          wget https://github.com/awslabs/git-secrets/archive/refs/heads/master.zip
          unzip master.zip 
          chmod -R 777 git-secrets-master
          cd git-secrets-master
          #git clone https://github.com/awslabs/git-secrets
          #cd git-secrets
          sudo make install
          cd ../secret-detection
          
      - name: git-secrets Scan
        run: |
          git secrets --install
          git secrets --register-aws
        
          git secrets --scan  &> git-secrets-scan-output.json || exit 0
          #git secrets --scan-history &> git-secrets-scan-history-output.json || exit 0
          
      - name: truffleHog Scan
        run: sudo truffleHog --regex --entropy=False --json >  truffleHog-scan-output.json         
      
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: |
            git-secrets-scan-output.json
            truffleHog-scan-output.json 
          
